# Generated by Django 2.0.3 on 2018-04-18 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('time_stamp', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Time member in/out')),
                ('is_go_in', models.BooleanField()),
                ('result_auth', models.BooleanField()),
                ('image', models.ImageField(upload_to='logs/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='member name')),
                ('email', models.EmailField(max_length=254)),
                ('card_id', models.TextField(verbose_name='card id')),
                ('course', models.TextField(null=True, verbose_name='course')),
                ('registered_day', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('research_about', models.TextField(null=True, verbose_name='research')),
                ('is_train', models.BooleanField(default=False)),
                ('threshold', models.IntegerField(null=True)),
                ('recognize_label', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas.Member'),
        ),
    ]
