# Generated by Django 2.0.3 on 2018-04-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_train',
            field=models.BooleanField(default=False),
        ),
    ]
