# Generated by Django 2.0.3 on 2018-03-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('time_stamp', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Time user in/out')),
                ('value', models.IntegerField(verbose_name='0/1 - out/in')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(verbose_name='user name')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('card_id', models.TextField(verbose_name='card id')),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas.User'),
        ),
    ]
